### ISSUE TITLE
ImageResizer doesn't work on gray images

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina-hub#111]
**Describe the bug**
`ImageResizer` doesn't work on gray images

**Describe how you solve it**

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINAHUB-23) by [Unito](https://www.unito.io/learn-more)

**Comment by lusloher** [comment]
We have the issue here twice, we should close one 👍 ?

**Comment by nan-wang** [comment]
duplicated with #165
