### ISSUE TITLE
feat(encoder): Add LASER support

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina-hub#127]
**Describe the feature**

Multilingual sentence encoding support with LASER

https://github.com/facebookresearch/LASER

It’s 14 language Tatoeba dataset performance is better than m-USE and at par with LaBSE. Supports 93 languages and is LSTM based.

**Proposal**
New laser module in /encoders/nlp

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINAHUB-33) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
That's a good idea! We're actively refactoring the hub this week. Let's get back to this after refactoring. Stay tuned!

**Comment by bhavsarpratik** [comment]
Sure Nan! Let me know when it’s complete and I will start working on this.

**Comment by nan-wang** [comment]
@bhavsarpratik hi, pal! Great job! Thanks for your contribution.
