### ISSUE TITLE
Loading binary files with FaissIndexer._load_training_data

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina-hub#1288]
The BaseNumpyIndexer.get_create_handler method stores vectors in gzip files. When the compression-level is zero, the vectors are stored as plain binary files. This case causes a problem when loading the training-data for the FaissIndexer.

Thus, I suggest that the FaissIndexer._load_training_data method should also support binary files. 
```
# Read from binary file:
with open(self.train_filepath, 'rb') as f:
    train_data = f.read()
```
This would enable us to train the FaissIndexer on the indexed vectors.

In addition, I'd like to mention that it was really hard for me to figure out how to use a plain FlatIndex (no training) for Faiss. Basically you just have to use "Flat" as you index_key and set is_trained to true in the meta. Maybe you want to add this to the documentations or examples.

All the best
Jan

**Comment by JoanFM** [comment]
Hey @janandreschweiger .

I think that #1289 would provide this feature.

**Comment by JoanFM** [comment]
Hey @janandreschweiger .

the changes were just merged and I think they should cover these functionalities.

**Comment by janandreschweiger** [comment]
Yes, awesome @JoanFM!

By the way, I love your work ethic. Only startups work on weekends :D
