### ISSUE TITLE
Implement update/delete for other VectorIndexers

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina-hub#1292]
Based on https://github.com/jina-ai/jina/pull/1415, implement the new mask filter logic for other VectorIndexers in the hub repo

**Comment by JoanFM** [comment]
This will only be needed in `MilvusIndexer` once it is rebuilt to the latest Milvus version and the indexer fixed

**Comment by JoanFM** [comment]
Closing this issue, as this is not needed now, since every `VectorIndexer` inherits `update` and `delete`
