### ISSUE TITLE
Add metadata in PDFExtractorSegmenter

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina-hub#1295]
User might want to search over indexed pdf pages but return the result showing where the text was matched. This requires PDFExtractorSegmenter to add `file name` and `page number` metadata for the user to link original PDF and page number

**Comment by carlosb1** [comment]
I did [modifications](https://github.com/jina-ai/jina-hub/compare/master...carlosb1:feat-metadata-pdf-extractor-segm?expand=1) to index filenames but I don't see exactly how to include the page_number if we work with a whole document

**Comment by JoanFM** [comment]
> I did [modifications](https://github.com/jina-ai/jina-hub/compare/master...carlosb1:feat-metadata-pdf-extractor-segm?expand=1) to index filenames but I don't see exactly how to include the page_number if we work with a whole document

It may not be possible using the current implementation and the libraries it is based on
