### ISSUE TITLE
Refactor Transformer tests

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina-hub#1296]
Refactor TransformerTorch and TransformerTF tests with a matrix of parameters by using `pytest parametrize`. The matrix should contain a few popular models worth testing with different `pooling` and `layer_index`

**Comment by tadej-redstone** [comment]
I can take care of this - I'm working on some other refactoring of transformer encoders anyways.

**Comment by JoanFM** [comment]
> I can take care of this - I'm working on some other refactoring of transformer encoders anyways.

That would be very cool. What refactoring are u working on?

**Comment by tadej-redstone** [comment]
> > I can take care of this - I'm working on some other refactoring of transformer encoders anyways.
> 
> That would be very cool. What refactoring are u working on?

What I described in #1291, some minor changes in documentation to synchronise with transformers package, and implementing reduce operations in native pytorch/tf - as this can lead to large speedups on GPU - same as in #399

**Comment by tadej-redstone** [comment]
And I am also considering adding AMP, for pytorch at least - see n #1283

**Comment by bhavsarpratik** [comment]
closed by #1344

**Comment by JoanFM** [comment]
This is not done in `TFTransformerEncoder` right?

**Comment by bhavsarpratik** [comment]
Ohh yes!

**Comment by bhavsarpratik** [comment]
@tadej-redstone Would you be interested in doing similar refactoring for `TransformerTFEncoder`? It shouldn't take much time.

**Comment by tadej-redstone** [comment]
Yes, I already have a branch ready doing this, I'm waiting first till #1527
is fixed
