### ISSUE TITLE
Remove jina from requirements.txt if jina is used as base image

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina-hub#1503]
Let's do it by parts.

In order to make sure that `jina version` is mantained to the intended one when the `automatic builds` appear, if 

`FROM jinaai/jina` is used as base image, then the jina from `requirements.txt` must be removed because I have observed, the last pip available version is installed and the one with the latest patch removed.

**Comment by tadejsv** [comment]
One question here: if another base image is to be used, how to make sure that the proper jina version is installed?

**Comment by JoanFM** [comment]
> One question here: if another base image is to be used, how to make sure that the proper jina version is installed?

That is another issue as in #1504

**Comment by JoanFM** [comment]
A lot of PRs open

#1502 
#1507 
...

**Comment by JoanFM** [comment]
Right now, missing `ZarrIndexer` and `AnnoyIndexer` which need to be fixed first
