### ISSUE TITLE
Add AlbumentationsCrafter

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina-hub#1907]
I propose that we add an [Albumentations](https://github.com/albumentations-team/albumentations) crafter, which could supplant/replace (with proper depreciation strategy) a lot of current image crafters, namely `CenterImageCropper`, `ImageCropper`, `ImageFlipper`, `ImageNormalizer`, `ImageResizer` and `RandomImageCropper`.

Here's are the reasons I believe this would be a good choice:
1. We replace these Jina "bespoke" crafters, with something that is [state-of-the-art in performance](https://github.com/albumentations-team/albumentations#benchmarking-results), [widely used](https://github.com/albumentations-team/albumentations#who-is-using-albumentations) and [extremely well documented](https://albumentations.ai/docs/).
2. Maintnance costs (in terms of labor) go down dramatically for these crafters :)
3. This not only replaces the current crafters, but adds 10s of new transform options, right out of the box.
4. We can implement chaining of transforms within the same crafter. Right now, to apply 2 transforms to an image, 2 crafters need to be added to the flow, and the images are passed between them. This adds a lot of unnecessary overhead. Albumentations supports effortless chaining of transforms, like this:
  ``` python
  transform = A.Compose([
    A.RandomCrop(width=256, height=256),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
])
  ```

In AlbumentationsCrafter, this could be done like this:
``` python
AlbumentationsCrafter(transforms = [
    {"RandomCrop": {"width": 256, "height":256}},
    {"HorizontalFlip": {"p": 0.5}},
    {"RandomBrightnessContrast": {"p": 0.2}}
])
```
I think this could also be used in `yaml` using the `with` argument? It's just a list/dict, nothing special here.
The object instatiation based on class name is also easy, [Hydra does it](https://hydra.cc/docs/next/patterns/instantiate_objects/overview/), for example.

If people think this is a good idea I could contribute a PR, and work on identifying examples where this new crafter could replace the existing ones :)

**Comment by JoanFM** [comment]
Hey @tadejsv ,

I do like the idea, I think it can be useful to wrap such a tool to profit from all their transformations

**Comment by carlosb1** [comment]
@tadejsv  are you working in this?

**Comment by tadejsv** [comment]
Yes, I plan to start soon

**Comment by carlosb1** [comment]
we can split this task, and we can work together if you want. I want to start this week,

**Comment by tadejsv** [comment]
I don't really think this requires more than one person
