### ISSUE TITLE
add an interactive builder to help user port executors

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina-hub#2]

**Comment by JoanFM** [comment]
Can this be closed?

**Comment by nan-wang** [comment]
nope, this ticket is still valid. Building an interactive UI for building/updating the images is not done yet.

**Comment by CatStark** [comment]
Is this ticket still valid? @nan-wang

**Comment by nan-wang** [comment]
> Is this ticket still valid? @nan-wang

Nope. As we are moving to `2.0`, this ticket is no longer valid. @CatStark
