### ISSUE TITLE
Use multi-stage builds to automatically discard testing artifacts

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina-hub#2567]
I think that executor docker images should be slightly restructured, so that testing artifacts are automatically discarded. The new images would look like so

``` dockerfile
FROM jinaai/jina AS base

# setup the workspace
COPY . /workspace
WORKDIR /workspace

# install the third-party requirements
RUN pip install -r requirements.txt

# for testing the image
FROM base
RUN pip install pytest && pytest

FROM base
ENTRYPOINT ["jina", "pod", "--uses", "config.yml"]
```

This way the testing part (including the installation of pytest) would not make it into the final image, and there would be no need to manually clean any artifacts (as currently has to be done in transformer images, for example).

**Comment by JoanFM** [comment]
Will then the requirements be discarded?  Also the workspace should be still mapped. 

The current structure is a template that can be changed depending on the needs and this can be a good possibility, and maybe can be used slowly as hub gets updated.

Is there any documentation on how this discards prrvious layers?

**Comment by tadejsv** [comment]
No, only things produced with ``RUN pip install pytest && pytest`` will be discarded, everything before will remain.

I believe if you check the [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) documentation they mention that things not copied from earlier stages (that you are not basing on) will be discarded.

Also, you can make this fun experiement. Create a `Dockerfile`
``` dockerfile
FROM ubuntu AS base
RUN echo 123 >> test.txt

FROM base
RUN echo 456 >> test.txt

FROM base
RUN echo 789 >> test.txt
```

Then create it and run
``` console
docker build -t test-ms .
docker run test-ms echo test.txt
```

You will get
```
123
789
```

which is consistent with only the middle layer being discarded (same pattern as my suggested image for executors).
