### ISSUE TITLE
Create Zero-Short transformer based classifiers

### ISSUE THREAD

**Issue by tadej-redstone** [jina-ai/jina-hub#3068]
I think a great addition to the hub would be a zero-shot classifier. You can read more about them [on this link](https://joeddav.github.io/blog/2020/05/29/ZSL.html), but in general they work like this:

1. Each of the possible categories is represented as a string (e.g. "Financial Document", "Legal Document", ...), and is transformed into an embedding
2. The object to categorize is also represented by a string ("This contract concerns the relationship between..."), which is then transformed into embeddings.
3. A distance metric is computed between the embeddings of categories and the item to categorize. From here it's simple to obtain a probability distribution on the categories and then return the assigned labels.

Their advantage is that they require zero training and can be adapted to a wide variety of classification tasks. They (some of the more sophisticated variants) also achieved quite great performance. For this reason I think they would fit in well in the Jina flow.

There are actually different interesting variants of this (as explained in the linked blog post), such as using a cloze task for classification, or, in case of single word categories, adjusting them to the embedding space through word2vec embeddings.

I think this is a great task for a first time contributor - the classifier would build upon the transformer encoders, but otherwise after some time I could take a shot at it as well.

**Comment by JoanFM** [comment]
Hey @tadej-redstone ,

This could be interesting as part of our `Classifier` BaseExecutor.  As per the interface described it would be a `classifier` assigning labels to each document. Currently we do not have any of these in our Hub but it can be a good addition.

As per the dependency on `TransformerEncoder`, one design decision of our Hub Executors is that they should be independent of each other even when code duplication may be involved. So even when sharing a lot of code with `TrasformerEncoders` they should be written from scratch.

**Comment by nan-wang** [comment]
I love the idea

**Comment by bsridatta** [comment]
Sounds interesting, I would like to contribute to this

**Comment by deepampatel** [comment]
I was using `ZeroShotClassifier` in my side project. 
Currently the way `BasePredictDriver` is implemented it requires the classification to be done using the embeddings generated by an encoder which is ahead in the flow.

gateway -> craft -> encode -> classify ....

The way i did it was i implemented a `BasePredictDriver` that used `extract_docs` to get text, then predict labels using zero shot classifier.

  ```
class CustomPredictDriver(BasePredictDriver):

      def _apply_all(
              self,
              docs: Iterable['jina_pb2.Document'],
              context_doc: 'jina_pb2.Document',
              field: str,
              *args,
              **kwargs,
      ) -> None:
          contents, docs_pts, bad_doc_ids = extract_docs(docs, embedding=False)
```
If i want to contribute `ZeroShotClassifier`  to jina hub, is it okay to do it in a way, it is dependent on a custom driver?
Is there other way you recommend?

**Comment by JoanFM** [comment]
Hey @deepampatel,

This would not be recommended, however I think youtr CustomDriver makes sense, and maybe we need to find a way to add it to the jina core.

I would even consider changing drastically the BasePredictDriver, or adding to it an option to see if the prediction must be done from the embedding or from the content.

You could do a PR in the core with these changes before submitting a PR in the hub.
