### ISSUE TITLE
check results with bert-base-uncased

### ISSUE THREAD

**Issue by JamesTang-jinaai** [jina-ai/jina-hub#328]
Someone from the community has proposed a [fix.](https://github.com/jina-ai/jina-hub/pull/327)

I will check these:

* Check whether the encoding results with bert-base-uncased are the same from TransformerTorchEncoder and TransformerTFEncoder
* Check whether it works for the BERT family, including DistilBERT, RoBERT
* Check whether it works for the non-BERT family, including XLM and CTRL

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINAHUB-54) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
related to #192

**Comment by JamesTang-jinaai** [comment]
In the test_encoding_results of both encoders put this assertion:

`np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])`

With this addition, every test_encoding_results failed. Including TransformerTorchEncoder and TransformerTFEncoder

**Comment by JamesTang-jinaai** [comment]
I encountered **killed** issue on my PC while running **TransformerTorchEncoder** with **CTRL** , probably because of the memory is fully used. I can noticed that the model is beyond **6G**, I will try to shut down some software and rerun the test again.

Here is the log

![image](https://user-images.githubusercontent.com/69177855/91839425-9dc39b80-ec81-11ea-8a08-6071fb40bdf3.png)

**Comment by JamesTang-jinaai** [comment]
Need priorities, cause there are plenty of **FAILED** cases need to be checked.

**Comment by JamesTang-jinaai** [comment]
Encoder:
* TransformerTorchEncoder
* TransformerTFEncoder

Pooling strategy that every Encoder uses:
* auto
* mean
* min
* max

Here is the summary: 
1. **Without** the assertion below, all test cases **PASSED**
`np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])`

2. **With** the assertion below, all `test_encoding_results` **FAILED**
`np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])`

3. Some test cases encountered **Killed** issue:
roberta-base
xlm-mlm-en-2048
ctrl

4. Here is the test cases list:
* bert-base-uncased
* xlnet-base-cased
* distilbert-base-uncased
* roberta-base
* xlm-mlm-en-2048
* ctrl

**Comment by JoanFM** [comment]
The issue described is not anymore there. Now different inputs lead to different outputs.

However,

I think with transformers v3.0.0 there is a better way to extract the last hidden state.

I am still not convinced that rhe reduction functions are working as they are expected to.

**Comment by JoanFM** [comment]
The problem seems solved partially, but I am not sure if the reduce functions are working properly.

**Comment by JamesTang-jinaai** [comment]
OK, I will try to check reduce functions

**Comment by bhavsarpratik** [comment]
Hi guys, let me know if you need any help. I had added the new test condition during my fix which checks if encoded_data[0] and encoded_data[1] are not same as it was the bug earlier. 

I suggest keeping smallest version of models of BERT and non-BERT families in test module for faster testing. If we are testing distilbert, we don’t need to test BERT as mechanism is same. I don’t think anyone will use CTRL for search and so it can be removed from test case.

**Comment by JamesTang-jinaai** [comment]
> Hi guys, let me know if you need any help. I had added the new test condition during my fix which checks if encoded_data[0] and encoded_data[1] are not same as it was the bug earlier.
> 
> I suggest keeping smallest version of models of BERT and non-BERT families in test module for faster testing. If we are testing distilbert, we don’t need to test BERT as mechanism is same. I don’t think anyone will use CTRL for search and so it can be removed from test case.

Thank you for your priorities! Don't worry, so far I didn't push any more test cases to the master. My target is to test whether it works for these models. We will host a Hackathon several days later, some guys may use it in various ways. BTW, please feel free to join our [Hackathon.](http://jinaxhackathon.ai/)

**Comment by JamesTang-jinaai** [comment]
I'm still on this code: `np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])`

The reason that the output data are different is that the first dimension of **Attention Mask** is different from the second, which you can see in the 8th column on the right panel.

![image](https://user-images.githubusercontent.com/69177855/91954270-2b5fc380-ed34-11ea-8ae2-e8dd8aaa8974.png)

After calculating, the 2 dimensions of **output** is shown on the right panel. The big difference is in the 8th row of the output data. The effect dues to `neg_mask = (mask_2d - 1) * (-1e10)`. Could anyone give me some references to check whether these reduce code is right or not?

![image](https://user-images.githubusercontent.com/69177855/91954587-93aea500-ed34-11ea-93a1-d14f80d9b13f.png)
![image](https://user-images.githubusercontent.com/69177855/91954660-b3de6400-ed34-11ea-87bb-f8b2c95a2339.png)

**Comment by JoanFM** [comment]
Just to make it clear:

` np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])` is supposed to FAIL.

**Comment by JamesTang-jinaai** [comment]
> Just to make it clear:
> 
> ` np.testing.assert_almost_equal(encoded_data[0], encoded_data[1])` is supposed to FAIL.

OK, thank you, Joan. This helps a lot

**Comment by JamesTang-jinaai** [comment]
To the first question, I've reproduced the issue, the result are quite the same.

Variable `encoded_data` relates to `TFEncoder`

![image](https://user-images.githubusercontent.com/69177855/91972184-e1cfa280-ed4c-11ea-98d4-95fe4c0f8f3a.png)

Variable `data1` relates to `TorchEncoder`

![image](https://user-images.githubusercontent.com/69177855/91972149-d67c7700-ed4c-11ea-8f7d-b38e7587e06a.png)
