### ISSUE TITLE
Docker image pod can't work properly

### ISSUE THREAD

**Issue by YueLiu-jina** [jina-ai/jina-hub#330]
Say for MinRanker, I run
`docker build -t minranker .`
`docker run minranker`
then there will be an error saying 'could not determine a constructor for the tag !MinRanker'. The problem is for almost all executors, same error appears not only in `docker run`, also when using them in examples.

This could be solved adding

```
metas:
  py_modules: __init__.py
```

to the config.yml

For reference, `docker run -it --entrypoint=/bin/bash minranker` can entry the container to check

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINAHUB-56) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
I think it must be due to the `jina` image it has been built with?

**Comment by YueLiu-jina** [comment]
it's jina 0.5.0, no problem with jina or python's version

**Comment by YueLiu-jina** [comment]
For reference `docker run -it --entrypoint=/bin/bash minranker` can entry the container to check

**Comment by YueLiu-jina** [comment]
The problem is PROBABLY because that we don't install hub in docker image, and the` config.yml` didn't attempt to find executor on local directory. So we need py_modules: to assign it

**Comment by YueLiu-jina** [comment]
seems docker package is also missing in our images, isn't it a dependency of jina?
