### ISSUE TITLE
faster reduce operations on cuda using cupy

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina-hub#399]
More than 10x faster `reduce operation` by doing them on GPU with `cupy`
Experiment result [notebook](https://colab.research.google.com/drive/1DEsqUIG2doF0wIy8Hmr4HvhXKXalu5iu?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINAHUB-59) by [Unito](https://www.unito.io/learn-more)

**Comment by tadejsv** [comment]
This can be closed, as transformers perform the reductions in native TF/Pytorch, which takes advantage of CUDA, if on GPU. @JoanFM
