### ISSUE TITLE
Lets keep is_reversed_score as a potential valid input argument to avoid breaking changes

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina-hub#4145]
https://github.com/jina-ai/jina-hub/blob/d89bc5e8f527f1212c3228a15775e222983c0087/rankers/SimpleAggregateRanker/__init__.py#L23

Lets add with deprecation warning the possibibility to use the old set of arguments.

**Comment by Yongxuanzhang** [comment]
Can we use deprecated_alias in hub?

**Comment by JoanFM** [comment]
> Can we use deprecated_alias in hub?
> #4146

Yes

**Comment by JoanFM** [comment]
@Yongxuanzhang is this closed?

**Comment by Yongxuanzhang** [comment]
> @Yongxuanzhang is this solved?

Yes. But just realize that should we add a test to it? If so, I will add a test accordingly

**Comment by JoanFM** [comment]
> > @Yongxuanzhang is this solved?
> 
> Yes. But just realize that should we add a test to it? If so, I will add a test accordingly

let's add it

**Comment by Yongxuanzhang** [comment]
> > > @Yongxuanzhang is this solved?
> > 
> > 
> > Yes. But just realize that should we add a test to it? If so, I will add a test accordingly
> 
> let's add it

Sure! I will do it today!
