### ISSUE TITLE
ImageTorchEncoder always loads mobilenet_v2

### ISSUE THREAD

**Issue by fsal** [jina-ai/jina-hub#419]
The class ImageTorchEncoder sets 'mobilenet_v2' as default CNN, but the ordering of the variables should be inverted from: 

https://github.com/jina-ai/jina-hub/blob/b2f41f7bfe978e9ef8b9688bf3d089114de3734e/encoders/image/ImageTorchEncoder/__init__.py#L47

to 

`self.model_name = model_name or 'mobilenet_v2'`

for proper overriding of the default.

**Comment by JoanFM** [comment]
Good catch! I would still have just `mobilenet_v2` as default parameter in the `__init__` ?

**Comment by fsal** [comment]
Sure, this is probably the best solution!
