### ISSUE TITLE
Synchronize issue between https://hubapi.jina.ai/images and hub.docker.com

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina-hub#4326]
https://hubapi.jina.ai/images is supposed to record the latest status of all the pod images.

`jinahub/pod.encoder.wav2vecspeechencoder` failed in building the docker image, https://github.com/jina-ai/jina-hub/runs/1957391213?check_suite_focus=true

However, https://hubapi.jina.ai/images still show that `jinahub/pod.encoder.wav2vecspeechencoder` is available

**Comment by deepankarm** [comment]
FIxed with https://github.com/jina-ai/cloud-ops/issues/67
