### ISSUE TITLE
Make ImageReader(Crafter) accept numpy images as input

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina-hub#478]
To me as an application developer, it would be useful to load ndarray images into the flow and apply image crafters on these images.

**Comment by nan-wang** [comment]
Hi, Florian! Great to see u! Is it what you are looking for?

```python
import numpy as np
from jina.flow import Flow

input_data = np.random.random((3, 8))

f = Flow().add(uses='_logforward')

with f:
    f.index_ndarray(input_data)
```

reference: https://docs.jina.ai/chapters/io/index.html#usage-of-index-ndarray

**Comment by JoanFM** [comment]
I will close this issue, we discussed in the PR that this functionality should not be part of ImageReader. The Flow already accepts inputing np arrays and working with them
