### ISSUE TITLE
REVIEW - Hub documentation, specially proper link to jinahub docker hub

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina-hub#4871]
@JoanFM yes, for example here: <https://docs.jina.ai/chapters/hub/publish-your-pod-image.html> and here: <https://docs.jina.ai/chapters/hub/use-your-pod.html>

But there are some other pages in the documentation with the wrong link too, just search for jinaai/hub. and you'll fine them.  
The first page (about publishing your pod) actually needs a more thorough update, as the structure of manifest.yml doesn't correspond to the actual one, and neither does the structure of the files inside jina-hub.

*Originally posted by @tadejsv in* [*https://github.com/jina-ai/jina-hub/issues/1347#issuecomment-752034221*](https://github.com/jina-ai/jina-hub/issues/1347#issuecomment-752034221)

┆Issue is synchronized with a [GitHub issue](https://github.com/jina-ai/jina-hub/issues/1499) by [Unito](https://www.unito.io/learn-more)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7157628

**Comment by rutujasurve94** [comment]
I've opened PR https://github.com/jina-ai/docs/pull/161 for this - updates the usage as per latest hub structure
