### ISSUE TITLE
add 'location' for all segmenters

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/jina-hub#5143]
Just like [Sentencizer](https://github.com/jina-ai/jina-hub/blob/cb7a176535eed6c86973465e8c6bfc977a4c572e/segmenters/nlp/Sentencizer/__init__.py#L74), we could add `location` for all other segmenters.

Potential benefits:

- Better UI at frontend, we can highlight the matches through location information
- Reconstruct from chunks to docs maybe?

**Comment by JoanFM** [comment]
if we do so, also add it to image , video and audio encoder, so that they can be reconstructed

**Comment by Yongxuanzhang** [comment]
> if we do so, also add it to image , video and audio segmenters so that they can be reconstructed

I changed the descriptions accordingly.

**Comment by shakurshams** [comment]
From the source code looks like the following segmenters need `'location'` implementation:
**NLP:**
  - SpacySentencizer
  - SlidingWindowSegmenter
  - PDFExtractorSegmenter
  - JiebaSegmenter
  - DeepSegmenter

**Image:**
  - FaceNetSegmenter

**Audio:**
  - AudioSlicer
  - SlidingWindowAudioSlicer

**Comment by nan-wang** [comment]
NLP:

- [x] SpacySentencizer #7981
- [x] SlidingWindowSegmenter#7982
- [ ] PDFExtractorSegmenter
- [ ] JiebaSegmenter
- [ ] DeepSegmenter

Image:

- [x] FaceNetSegmenter #7983

Audio:

- [x] AudioSlicer #7984
- [x] SlidingWindowAudioSlicer #7985

**Comment by Yongxuanzhang** [comment]
Since we are going to Jina 2.0, is this ticket still available?

**Comment by nan-wang** [comment]
> Since we are going to Jina 2.0, is this ticket still available?

No, it is no longer valid.
