### ISSUE TITLE
Remove `array2pb` and `pb2array` function from hub

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina-hub#578]
The two above mentioned functions were removed from jina due to a refactoring. They are not needed anymore, but in some parts of the hub still existent. That should be refactored.

The PR in jina in which the refactoring happened is:

https://github.com/jina-ai/jina/commit/008638d3e61c20c585b376ea003be712123a6eb2#diff-78bac2537fa2f301f32229a6b3db4bc61686bde54b51ee15c94bfcbb77271feb

**Comment by JoanFM** [comment]
are they present in tests? or in executors themselves? If in executors it is quite a design flaw I think

**Comment by maximilianwerk** [comment]
> are they present in tests? or in executors themselves? If in executors it is quite a design flaw I think

only in tests.

**Comment by JoanFM** [comment]
Can't find these usage anymore anywhere in the hub
