### ISSUE TITLE
Transformer Torch Sequence Classifier

### ISSUE THREAD

**Issue by mezig351** [jina-ai/jina-hub#6191]
Hi, would it be a useful implementation for `jina-hub` to add a text (sequence) classification wrapper for [huggingface sequence classification models](https://huggingface.co/transformers/usage.html#sequence-classification)? One common example of this in NLP is sentiment analysis. I believe it would work with all the pretrained models listed [here](https://huggingface.co/models?pipeline_tag=text-classification).

As the recent classifier examples, this would have its own encoder within, and would work independently from existing `jina-hub` encoders. 

I could volunteer to do this if it sounds interesting ✌️

**Comment by FionnD** [comment]
Hi @mezig351 

Great idea! I've assigned you the ticket, if you need any support please join our slack community and ask there :)
