### ISSUE TITLE
writing to hub db failing since 1.0.10

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina-hub#6840]
None of the builds (during CD or CI for updater action) are updated in the database since 1.0.10. 

Hints so far:
- Error status codes were getting ignored in `hubapi/remote.py`. Hence no errors during build (fixed in https://github.com/jina-ai/jina/pull/2225)
- Seems related to the way we login while using `hub-builder` action, as the write to db passed successfully during local run.

**Comment by nan-wang** [comment]
Good catch!

**Comment by deepankarm** [comment]
The issue was with github token. 

`${{ github.token }}` is not a valid user according to github api. Every user of `hub-builder-action` should create a PAT & use that with variable `jina_hub_token`

Got fixed for `jina-hub` repo. Need to be added in [docs](https://docs.jina.ai/chapters/hub/guides/hub-builder/)

![image](https://user-images.githubusercontent.com/9050737/112140134-a23daa80-8bf9-11eb-9a21-4bd78a294d06.png)
