### ISSUE TITLE
VectorIndexer does not filter results based on `deleted` mask

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina-hub#7980]
A lot of the `VectorIndexers` implemented in `jina-hub` do not take into account deleted documents when querying

**Comment by FionnD** [comment]
@JoanFM this a bug?

**Comment by JoanFM** [comment]
well, it can be seen as it is, these vectorindexers do not consider `deleted vectors` in the `mask`. In the future this will not matter, but at this stage is incoherent

**Comment by FionnD** [comment]
Could you list them here? I can just add a note to the README of each one for the moment. I don't think we have the capacity to fix it.

**Comment by FionnD** [comment]
@JoanFM

**Comment by JoanFM** [comment]
my bad, I saw the implementation and should not be a problem
