### ISSUE TITLE
ModuleNotFoundError found even when package has been installed inside image.

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina-hub#874]
**Issue**
Something wrong with hub images, ModuleNotFoundError found even when package has been installed inside image.

One can see in most of the hub executors that failed to bump versions that the import of some packages failed while they have been successfully installed.

Good examples #867

**Comment by rutujasurve94** [comment]
Testing with : `jina hub build --prune-images --raise-error --host-info --test-uses --daemon .`
PR under progress: https://github.com/jina-ai/jina/pull/1361

**Comment by JoanFM** [comment]
Closed by  jina-ai/jina#1361
